# Generated by Django 4.2.7 on 2026-01-23 19:00

from django.db import migrations


def create_user_profiles(apps, schema_editor):
    """Create UserProfile for all existing users"""
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('store', 'UserProfile')
    
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


def reverse_create_user_profiles(apps, schema_editor):
    """Reverse migration - delete all UserProfiles"""
    UserProfile = apps.get_model('store', 'UserProfile')
    UserProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_order_order_type_product_is_wholesale_available_and_more"),
    ]

    operations = [
        migrations.RunPython(create_user_profiles, reverse_create_user_profiles),
    ]
