# Generated by Django 4.2.7 on 2026-04-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_create_user_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
